### Good Weather Tests:


### Get list of RMA
GET http://localhost:3000/rma
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get list of RMA successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
        client.assert(Array.isArray(response.body), "Expected body to be an array");
    });
%}


### Get RMAs with date
GET http://localhost:3000/rma/withDates
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get RMAs with date successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
        client.assert(Array.isArray(response.body), "Expected body to be an array");
    });
%}



### Get RMAs per month
GET http://localhost:3000/rma/monthly
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get RMAs per month successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
        client.assert(Array.isArray(response.body), "Expected body to be an array");
    });
%}



### Get list of return products
GET http://localhost:3000/rma/returns/Products
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get list of return products successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
        client.assert(Array.isArray(response.body), "Expected body to be an array");
    });
%}



### Get RMA by barcode
GET http://localhost:3000/rma/barcode
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get RMA by barcode successfully", function () {
        client.assert(response.status === 200, "Expected RMA information");
        client.assert(Array.isArray(response.body), "Expected body to be an array");
    });
%}




### Get status of an RMA
GET http://localhost:3000/rma/3/status
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get status of an RMA successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
        client.assert(typeof response.body === 'string', "Expected body to be a string");
    });
%}



### Get customer of an RMA
GET http://localhost:3000/rma/5/customer
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get customer of an RMA successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
        client.assert(typeof response.body === 'object', "Expected body to be an object");
    });
%}



### Get products of an RMA
GET http://localhost:3000/rma/8/products
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get products of an RMA successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
        client.assert(Array.isArray(response.body), "Expected body to be an array");
    });
%}



### Get quantity of an RMA
GET http://localhost:3000/rma/14/quantity
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get quantity of an RMA successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
        client.assert(typeof response.body === 'number', "Expected body to be a number");
    });
%}



### Get returns by user ID
GET http://localhost:3000/rma/returns/1
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get returns by user ID successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
        client.assert(Array.isArray(response.body), "Expected body to be an array");
    });
%}


### Bad Weather Tests:

### Get list of RMA
GET http://localhost:3000/rmas
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get list of RMA failure", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}


### Get RMAs with date
GET http://localhost:3000/rmas/withDate
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get RMAs with date failure", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}



### Get RMAs per month
GET http://localhost:3000/rmas/monthly??
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get RMAs per month failure", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}



### Get list of return products
GET http://localhost:3000/rmas/returns/Products
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get list of return products failure", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}



### Get RMA by ID
GET http://localhost:3000/rmas/9999
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get RMA by non-existent ID", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}



### Get total price of an RMA
GET http://localhost:3000/rmas/178/totalPrice
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get total price of non-existent RMA", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}



### Get customer of an RMA
GET http://localhost:3000/rmas/34/customers
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get customer of non-existent RMA", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}


### Get products of an RMA
GET http://localhost:3000/rmas/56/products
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get products of non-existent RMA", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}



### Get list of RMA
GET http://localhost:3000/rmas
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get list of RMAs should return 404 on failure", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}




### Get RMAs with date
GET http://localhost:3000/rmas/:withDates3??
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get RMAs with dates should return 404 on failure", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}




### Get list of return products
GET http://localhost:3000/rmas/returns/Products
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get list of return products should return 404 on failure", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}

### Get total price of a non-existent RMA
GET http://localhost:3000/rma/999/totalPrice
Content-Type: application/json
Accept: application/json

> {%
    client.test("Get total price of a non-existent RMA should return 404", function() {
        client.assert(response.status === 404, "Expected response status to be 404");
    });
%}


